# Generated by Django 5.1.5 on 2026-06-11 17:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("core", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Bet",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("bet_type", models.CharField(max_length=50)),
                ("prediction", models.CharField(max_length=50)),
                ("odds", models.DecimalField(decimal_places=2, max_digits=8)),
                ("stake", models.DecimalField(decimal_places=2, max_digits=15)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("won", "Won"),
                            ("lost", "Lost"),
                            ("cancelled", "Cancelled"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                (
                    "payout",
                    models.DecimalField(decimal_places=2, default=0, max_digits=15),
                ),
                ("placed_at", models.DateTimeField(auto_now_add=True)),
                ("resolved_at", models.DateTimeField(blank=True, null=True)),
                (
                    "fixture",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="bets",
                        to="core.fixture",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="bets",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="BettingOdds",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "bet_type",
                    models.CharField(
                        help_text="match_winner or exact_score", max_length=50
                    ),
                ),
                (
                    "odds_data",
                    models.JSONField(help_text="Full odds object from API-Football"),
                ),
                ("fetched_at", models.DateTimeField(auto_now_add=True)),
                (
                    "fixture",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="betting_odds",
                        to="core.fixture",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Betting odds",
                "unique_together": {("fixture", "bet_type")},
            },
        ),
    ]
