# Generated by Django 5.1.5 on 2026-06-11 17:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Country",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                (
                    "code",
                    models.CharField(
                        help_text="ISO country code, e.g. BR, AR",
                        max_length=5,
                        unique=True,
                    ),
                ),
                ("flag_url", models.URLField(blank=True)),
                (
                    "api_team_id",
                    models.IntegerField(help_text="API-Football team ID", unique=True),
                ),
                ("is_eliminated", models.BooleanField(default=False)),
                (
                    "group",
                    models.CharField(
                        blank=True, help_text="e.g. Group A", max_length=10
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Countries",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="Fixture",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "api_fixture_id",
                    models.IntegerField(
                        help_text="API-Football fixture ID", unique=True
                    ),
                ),
                ("kick_off", models.DateTimeField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("scheduled", "Scheduled"),
                            ("live", "Live"),
                            ("finished", "Finished"),
                            ("postponed", "Postponed"),
                            ("cancelled", "Cancelled"),
                        ],
                        default="scheduled",
                        max_length=20,
                    ),
                ),
                ("home_score", models.IntegerField(blank=True, null=True)),
                ("away_score", models.IntegerField(blank=True, null=True)),
                (
                    "round",
                    models.CharField(
                        blank=True,
                        help_text="e.g. Group A - 1, Round of 16",
                        max_length=100,
                    ),
                ),
                ("venue", models.CharField(blank=True, max_length=200)),
                (
                    "stats_processed",
                    models.BooleanField(
                        default=False,
                        help_text="Whether fantasy points have been calculated",
                    ),
                ),
                (
                    "away_team",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="away_fixtures",
                        to="core.country",
                    ),
                ),
                (
                    "home_team",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="home_fixtures",
                        to="core.country",
                    ),
                ),
            ],
            options={
                "ordering": ["kick_off"],
            },
        ),
        migrations.CreateModel(
            name="Player",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("photo_url", models.URLField(blank=True)),
                (
                    "api_player_id",
                    models.IntegerField(
                        help_text="API-Football player ID", unique=True
                    ),
                ),
                (
                    "position",
                    models.CharField(
                        choices=[
                            ("GK", "Goalkeeper"),
                            ("DEF", "Defender"),
                            ("MID", "Midfielder"),
                            ("FWD", "Forward"),
                        ],
                        max_length=3,
                    ),
                ),
                (
                    "market_value",
                    models.DecimalField(
                        decimal_places=2, default=5000000, max_digits=15
                    ),
                ),
                (
                    "total_fantasy_points",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                (
                    "is_available",
                    models.BooleanField(
                        default=True, help_text="Available for draft/transfer"
                    ),
                ),
                ("jersey_number", models.IntegerField(blank=True, null=True)),
                (
                    "country",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="players",
                        to="core.country",
                    ),
                ),
                (
                    "owner",
                    models.ForeignKey(
                        blank=True,
                        help_text="Current owner (exclusive ownership)",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="owned_players",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["country", "position", "name"],
            },
        ),
        migrations.CreateModel(
            name="PlayerMatchStats",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("minutes_played", models.IntegerField(default=0)),
                (
                    "position_played",
                    models.CharField(
                        blank=True,
                        help_text="Position in this match: G/D/M/F",
                        max_length=3,
                    ),
                ),
                (
                    "rating",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=4, null=True
                    ),
                ),
                ("was_substitute", models.BooleanField(default=False)),
                ("goals", models.IntegerField(default=0)),
                ("assists", models.IntegerField(default=0)),
                ("goals_conceded", models.IntegerField(default=0)),
                ("saves", models.IntegerField(default=0)),
                ("passes_total", models.IntegerField(default=0)),
                ("passes_key", models.IntegerField(default=0)),
                (
                    "pass_accuracy",
                    models.CharField(blank=True, help_text="e.g. '85%'", max_length=10),
                ),
                ("tackles", models.IntegerField(default=0)),
                ("interceptions", models.IntegerField(default=0)),
                ("blocks", models.IntegerField(default=0)),
                ("duels_total", models.IntegerField(default=0)),
                ("duels_won", models.IntegerField(default=0)),
                ("dribbles_attempted", models.IntegerField(default=0)),
                ("dribbles_success", models.IntegerField(default=0)),
                ("shots_total", models.IntegerField(default=0)),
                ("shots_on_target", models.IntegerField(default=0)),
                ("fouls_drawn", models.IntegerField(default=0)),
                ("fouls_committed", models.IntegerField(default=0)),
                ("yellow_cards", models.IntegerField(default=0)),
                ("red_cards", models.IntegerField(default=0)),
                ("penalties_scored", models.IntegerField(default=0)),
                ("penalties_missed", models.IntegerField(default=0)),
                ("penalties_saved", models.IntegerField(default=0)),
                ("penalties_won", models.IntegerField(default=0)),
                (
                    "fantasy_points",
                    models.DecimalField(decimal_places=2, default=0, max_digits=8),
                ),
                (
                    "fixture",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="player_stats",
                        to="core.fixture",
                    ),
                ),
                (
                    "player",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="match_stats",
                        to="core.player",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Player match stats",
                "unique_together": {("player", "fixture")},
            },
        ),
    ]
